### ISSUE TITLE
Event Listener doesn't seem to work

### ISSUE THREAD

**Issue by ibrahimdolas** [QuickBlox/quickblox-javascript-sdk#402] opened 2020-09-22 06:48 UTC
I'm developing a video chat web app with quickblox js sdk. Everything is fine until session.call(). QB.webrtc.onCallListener function doesn't work. QB.webrtc.onUserNotAnswerListener doesn't work either. 

**Environment details**
MacOs 10.15.16, Google Chrome 85.0.4183.102, JavaScriptSDK 2.12.9

**Did this work before?**
Nope

**Expected behavior**
1-Opponent should have reach information that call has initiated by initiator. 
2- Initiator should have reach information that call hasn't answered.

**Actual behavior**
Nothing happens.

**Logs**
*(please, switch on a [debugging mode](http://quickblox.com/developers/Javascript#Configuration) and share us outputs uses github [gist](https://gist.github.com/))*
`1087
quickblox.js:4 2.12.9
DevTools failed to load SourceMap: Could not load content for http://localhost/assets/js/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
quickblox.min.js:1 [QBWebRTC]: Call, extension: {}
quickblox.min.js:1 [QBWebRTC]: _createPeer, iceServers: {"iceServers":[{"url":"stun:turn.quickblox.com","username":"quickblox","credential":"baccb97ba2d92d71e26eb9886da5f1e0","urls":"stun:turn.quickblox.com"},{"url":"turn:turn.quickblox.com:3478?transport=udp","username":"quickblox","credential":"baccb97ba2d92d71e26eb9886da5f1e0","urls":"turn:turn.quickblox.com:3478?transport=udp"},{"url":"turn:turn.quickblox.com:3478?transport=tcp","username":"quickblox","credential":"baccb97ba2d92d71e26eb9886da5f1e0","urls":"turn:turn.quickblox.com:3478?transport=tcp"}]}
quickblox.min.js:1 [QBWebRTC]: RTCPeerConnection init. userID: 122492328, sessionID: 2afd5984-f8db-4277-b9e0-40d9e6616345, type: offer
quickblox.min.js:1 [QBWebRTC]: getAndSessionDescription success
quickblox.min.js:1 [QBWebRTC]: _startDialingTimer, dialingTimeInterval: 5000
quickblox.min.js:1 [QBWebRTC]: _dialingCallback, answerTimeInterval: 0
quickblox.min.js:1 [QBWebRTC]: _dialingCallback, answerTimeInterval: 5000
quickblox.min.js:1 [QBWebRTC]: _dialingCallback, answerTimeInterval: 10000
quickblox.min.js:1 [QBWebRTC]: _dialingCallback, answerTimeInterval: 15000
quickblox.min.js:1 [QBWebRTC]: _dialingCallback, answerTimeInterval: 20000
quickblox.min.js:1 [QBWebRTC]: _dialingCallback, answerTimeInterval: 25000
quickblox.min.js:1 [QBWebRTC]: _dialingCallback, answerTimeInterval: 30000
quickblox.min.js:1 [QBWebRTC]: _dialingCallback, answerTimeInterval: 35000
quickblox.min.js:1 [QBWebRTC]: _dialingCallback, answerTimeInterval: 40000
quickblox.min.js:1 [QBWebRTC]: _dialingCallback, answerTimeInterval: 45000
quickblox.min.js:1 [QBWebRTC]: _dialingCallback, answerTimeInterval: 50000
quickblox.min.js:1 [QBWebRTC]: _dialingCallback, answerTimeInterval: 55000
quickblox.min.js:1 [QBWebRTC]: _dialingCallback, answerTimeInterval: 60000
quickblox.min.js:1 [QBWebRTC]: _clearDialingTimer
quickblox.min.js:1 [QBWebRTC]: Answer timeout callback for session 2afd5984-f8db-4277-b9e0-40d9e6616345 for user 122492328
quickblox.min.js:1 [QBWebRTC]: All peer connections closed: true`
**Steps to reproduce the behavior**

`"use strict";

console.log(QB.buildNumber);
console.log(QB.version);

$('#me').html('<video style="width: 100%!important; height: 100%!important; object-fit: cover" id="myVideo"></video>');

function handleError(err) {
	swal({
		title: 'Hata!',
		text: err,
		icon: 'error',
		buttons: false,
		timer: 3000
	});
}

var mediaParams = {
	audio: true,
	video: true,
	options: {
		muted: false,
		mirror: true
	},
	elemId: 'myVideo'
};

var chatParams = {
	jid: userId + '-' + appId + '@' + qbConfig.endpoints.chat,
	password: ups
};

QB.init(sessionToken, appId, null, qbConfig);

QB.chat.connect(chatParams, function (error, contactList) {
	if (error) {
		handleError(error);
	} else {
		$('.start-call').removeClass('d-none').on('click', function () {
			
			var calleesId = [opp];
			var sessionType = QB.webrtc.CallType.VIDEO;
			var additionalOptions = {};
			
			var session = QB.webrtc.createNewSession(calleesId, sessionType, null, additionalOptions);
			
			session.getUserMedia(mediaParams, function (error, stream) {
				if (error) {
					handleError(error);
				} else {
					session.call({}, function (error) {
						if (error) {
							handleError(error);
						} else {
							QB.webrtc.onUserNotAnswerListener = function (session, userId) {
								console.log(session);
								console.log(userId);
							}
							
						}
					})
				}
			})
		})
		
		QB.webrtc.onCallListener = function (session, extension) {
			console.log(session);
			console.log(extension);
		}
		
	}
});`

**Any others comments?**
PS: I'm defining variables on html, so it's not an "undefined variable" problem.

**Comment by ghost** [comment] 2021-10-07 15:20
@ibrahimdolas 
Hello,

This is Nikolay from QuickBlox support.

Please let me know if the issue is still relevant and if it is reproduced on the latest version of our SDK and on the updated sample:
[https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10](https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10)
[https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/webrtc](https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/webrtc)

Also, please make sure that you followed our documentation:
[https://docs.quickblox.com/docs/js-video-calling](https://docs.quickblox.com/docs/js-video-calling)

**Comment by ghost** [comment] 2021-12-07 13:10
@ibrahimdolas The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed as completed by ghost** 2021-12-07 13:10 UTC
