### ISSUE TITLE
Re-Initialization Quickblox (Javascript SDK)

### ISSUE THREAD

**Issue by williamtran1988** [QuickBlox/quickblox-javascript-sdk#347] opened 2018-07-23 03:31 UTC
Hi All,

Are there any way to re-init by calling QB.init again with different configuration informations? I am facing an error when i did it:

Uncaught TypeError: Cannot read property 'send' of null
    at a.Websocket._onIdle (quickblox.min.js:15)

Could you please help me on this?
BR,
William Tran.

**Comment by williamtran1988** [comment] 2018-07-23 15:46
<img width="1350" alt="screen shot 2018-07-23 at 10 46 08 pm" src="https://user-images.githubusercontent.com/22092643/43087519-45c46714-8eca-11e8-8944-7f6e93c29b4d.png">

**Comment by vadimkhmyrovqb** [comment] 2018-12-20 14:43
closing this issue as a duplicate of #351

**Closed as completed by vadimkhmyrovqb** 2018-12-20 14:43 UTC

**Comment by karan118** [comment] 2020-11-30 10:01
Thanks williamtran1988 it work for me
