### ISSUE TITLE
NPM Install Not Working Version 2.12.0

### ISSUE THREAD

**Issue by itsaboutcode** [QuickBlox/quickblox-javascript-sdk#355] opened 2018-09-10 10:36 UTC
**Environment details**
*SDK Version 2.12.0*

**Did this work before?**
No Idea

**Expected behavior**
Library should be installed

**Actual behavior**
Library is not installing properly due to npm security audits

**Steps to reproduce the behavior**
Just install the latest version with npm in React App

**Attached Screenshots**

<img width="570" alt="screen shot 2018-09-10 at 2 59 48 pm" src="https://user-images.githubusercontent.com/204423/45292536-f470c180-b50e-11e8-9ab5-49c177c6f156.png">
<img width="789" alt="screen shot 2018-09-10 at 3 00 02 pm" src="https://user-images.githubusercontent.com/204423/45292537-f470c180-b50e-11e8-8961-feb7793a3dca.png">
<img width="1030" alt="screen shot 2018-09-10 at 3 21 37 pm" src="https://user-images.githubusercontent.com/204423/45292538-f470c180-b50e-11e8-933f-e2d718bf91d0.png">

**Comment by obrunsmann** [comment] 2018-10-19 11:27
Any solution here? Same issue.

**Comment by vadimkhmyrovqb** [comment] 2018-12-20 14:38
@itsaboutcode @obrunsmann is this issue reproduced in latest SDK version 2.12.2 ?

**Comment by obrunsmann** [comment] 2018-12-21 16:52
@vadimkhmyrovqb Sorry - we decided to not use Quickblox among other things because of the installation issues.

**Comment by vadimkhmyrovqb** [comment] 2018-12-22 09:01
The issue was resolved in version 2.12.1

**Closed as completed by vadimkhmyrovqb** 2018-12-22 09:01 UTC
