### ISSUE TITLE
No response from QB.chat.muc.join(dialogJid) method

### ISSUE THREAD

**Issue by 123AndGo** [QuickBlox/quickblox-javascript-sdk#102] opened 2016-01-22 16:48 UTC
Hello, since yesterday (21/01/2016) our group chats aren't working because we get no response after calling the QB.chat.muc.join(dialogJid) method. We also see that automatic "presence" messages also don't get any responses.

The users login and connect to the chat (QB.chat.connect()) without any problem, but the join method suddenly stopped working without us having made any changes.

You can test this issue with this code (we have tested it on v1.16.1 and v2.0.3 of the SDK):

``` javascript
var CONFIG = {  
    chatProtocol: {
        active: 2 // set 1 to use BOSH, set 2 to use WebSockets (default)
    },
    debug: {mode: 1} // set DEBUG mode
};

var CREDENTIALS = {
  appId: 34012,
  authKey: 'pwSCOResb4R2Lka',
  authSecret: 'E4sztXGxw5Qk8md'
};

QB.init(CREDENTIALS.appId, CREDENTIALS.authKey, CREDENTIALS.authSecret, CONFIG);

QB.createSession(function(e, r){
    var params = {login: 'test@test.com', password: '12345678'};
    QB.login(params, function(e,r){
        if(r) {                        
            QB.chat.connect({userId: r.id, password: '12345678'}, function(e,roster){
                if(!e){
                    QB.chat.muc.join("34012_56a15ec7a0eb4791ae0003cc@muc.chat.quickblox.com",function(r){console.log(r);});
                }
            });
        }
    });
});
```

And this are the screenshots of the console logs:
![ss1](https://cloud.githubusercontent.com/assets/11200152/12516639/77c3476a-c0fc-11e5-9f12-50e5afa645e0.jpg)
![ss2](https://cloud.githubusercontent.com/assets/11200152/12516701/db688eec-c0fc-11e5-9d14-b45e9a19da27.jpg)
![ss3](https://cloud.githubusercontent.com/assets/11200152/12516711/e3911cb0-c0fc-11e5-92d1-be16bed9ebc6.jpg)

This is really urgent for us because we haven't been able to do any further development and we have a very close deadline for launching the chat feature of our group dating app, so we would really appreciate your help.

Thank you very much. All my best.

**Comment by 123AndGo** [comment] 2016-01-22 17:48
Hello again! I've just performed a new test by creating a test app on a co-developer's account and on that account everything is working well, so the problem seems to be with my developer's account.

I checked if maybe there was some mistake that caused a massive API calls avalanche but I see in the stats page that the amount of my app's API calls count is very low. So, I don't know what caused this blocking on my account.

I would really appreciate your help on un-blocking my account. All my best.

**Comment by juvaly** [comment] 2016-01-23 05:58
I'm having the same issue. Callback from join not firing.

EDIT: The callback is fired, and i can send messages, when i use the account owner user. For any other user it doesn't work.

**Comment by coredream** [comment] 2016-01-24 03:24
I'm experiencing the exact same problem, but with the quickblox-ios-sdk (just adding to this thread since I was curious if anyone else was having this problem).  Callback from join not firing in my iOS app:

[dialog joinWithCompletionBlock:^(NSError *error)

I also started seeing this on Jan 21.

**Comment by dimaspirit** [comment] 2016-01-25 12:47
Hi everyone, could you check this one more time? And will confirm if the issue still reproduce.

**Comment by juvaly** [comment] 2016-01-25 16:44
seems to be working now. what was the problem?

**Comment by dimaspirit** [comment] 2016-01-25 16:58
Good!
It looks like we had a problem on the server side, but we fixed.

**Comment by 123AndGo** [comment] 2016-01-25 17:45
It is working for us too. Thank you very much!

**Comment by himanshunimje** [comment] 2016-06-17 09:30
I seem to be having this problem now. While using the function retrieveChatDialogs(), browser console is showing an error on the following lines of code:

```
// join room
        if (item.type != 3) {
          QB.chat.muc.join(item.xmpp_room_jid, function() {
             console.log("Joined dialog "+dialogId);
          });
        }
```

Attaching the browser console for further clarity.

<img width="1280" alt="screen shot 2016-06-17 at 2 57 50 pm" src="https://cloud.githubusercontent.com/assets/11310866/16146503/f9e564c2-349b-11e6-85cb-ff2593f2a983.png">

Is this an issue on server side or do I need to change the code from my end? The exact same code was working perfectly fine yesterday, but I am receiving this error today.

**Comment by k1master** [comment] 2016-06-21 07:52
I also have that issue. Code is nearly all the same with sample chat app. Finally, I replaced all the credentials in the sample chat app, and it's not working either. It seems like my qb account is not working for group chat. Why is this happening?
There aren't many api calls.

**Comment by k1master** [comment] 2016-06-22 01:07
I have found the a thing. Maybe it could help solving this issue.
It works with the users I made in admin panel when I join to group chat. That group chat was also made in admin panel. But when I try to join the group chat that is made from server backend, which calls QB Restful API, it doesn't work.

**Comment by dimaspirit** [comment] 2016-06-22 07:57
Hi everybody, 
yes, we have the issue on backend side.
We need to know endpoints of your instance (if you don't use QB instance) to fix that issue.
So, write here what instance you use and we will fix it.

**Comment by k1master** [comment] 2016-06-22 09:59
I have figured out.
In my case, the reason was from your session creation API.
API Documentation says to use [POST] /session.json, but the users with this API is not working for group chat. I used /auth.json for session creation and used signup RESTful api, and it is working now.
This is not account problem.
I think you should check that API or update documentation.

**Comment by himanshunimje** [comment] 2016-06-23 06:14
Hi,

I am using the javascript SDK to create session and login a QB user. Hence, following are the javascript lines of code which uses quickblox.min.js to access the API's:

`var params = { 'login': 'testuser_1', 'password': '*********'};
QB.createSession(function(err, res) {
    QB.login(params, function(err, user){
        setupStickerPipe();
        retrieveChatDialogs();
        setupAllListeners();
        setupMsgScrollHandler();
    }
}`

Let me know if this is the information that you needed.

**Comment by k1master** [comment] 2016-06-23 07:00
@himanshunimje , your problem can be fixed by calling QB.chat.connect() function.
Please refer this code.

```
QB.createSession(credentials, function(err, result){
                if (result){ // session created? (login success)
                    console.log(result);

                    credentials.user_id = result.user_id;

                    QB.chat.connect({
                        userId: result.user_id,
                        password: credentials.password
                    }, function(err, res){
                        if (res){
                            console.log(res);

                            QB.chat.dialog.list(null, function(err, dialogs){
                                dialogs.items.forEach(function(dlg, i, arr){
                                    if (dlg.name.startsWith('call')){
                                        return;
                                    }
                                    if (dlg.type == 2){
                                        service.chatIds[dlg._id] = false;
                                        QB.chat.muc.join(dlg.xmpp_room_jid, function(){
                                            service.chatIds[dlg._id] = true;
                                            console.log("Joined dialog " + dlg._id + " xmpp " + dlg.xmpp_room_jid);
                                        });
...
```

This code works with users that are created using session from /auth.json API, but /session.json API.

**Comment by himanshunimje** [comment] 2016-06-23 07:26
@Alex--Jin : That solves the issue. Thanks for helping out.

PS: I am getting the following error in browser console while retrieving chat dialogs of a user i.e. using the same retrieveChatDialogs() function:

Uncaught InvalidStateError: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state.

I am assuming that this is an invalid state error which gets solved when the WebSocket is connected. Should I be worried about this error?

**Comment by k1master** [comment] 2016-06-23 10:46
No. You don't need.
@himanshunimje

**Closed as completed** 2017-06-30 12:28 UTC
