### ISSUE TITLE
On page load,  display all dialogs in left panel.

### ISSUE THREAD

**Issue by Jignasa10** [QuickBlox/quickblox-javascript-sdk#386] opened 2020-01-31 11:27 UTC
Currently, when I load an SDK I'm not getting all dialogs. Please assist me how can I do?
I'm Using Sample Chat for demo.

Currently what happens If someone sends me to message then show the dialog. if I send a message to another show left panel dialog. But  if a reload page I can not show dialog which has a previous chat.

**Comment by ghost** [comment] 2021-10-07 15:17
@Jignasa10 
Hello,

This is Nikolay from QuickBlox support.

Please let me know if the issue is still relevant and if it is reproduced on the latest version of our SDK and on the updated sample:
[https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10](https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10)
[https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/chat](https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/chat)

**Comment by ghost** [comment] 2021-12-07 13:08
@Jignasa10 The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed as completed by ghost** 2021-12-07 13:08 UTC
