### ISSUE TITLE
Unexpected `toLowerCase` exception thrown on unauthorized login

### ISSUE THREAD

**Issue by joelhelbling** [QuickBlox/quickblox-javascript-sdk#406] opened 2020-12-01 16:25 UTC
*Help avoid duplicate issue reports, check [existing issues](https://github.com/QuickBlox/quickblox-javascript-sdk/issues)*

**Environment details**
*(Operating system, browser information, SDK version)*
Environment: NodeJS 12.16.2
SDK version 2.13.2

**Did this work before?**
This error was not thrown before.

**Expected behavior**
Invalid auth returns error with `401`.

**Actual behavior**
Exception thrown: `TypeError: Cannot read property 'toLowerCase' of undefined`

**Logs**
*(please, switch on a [debugging mode](http://quickblox.com/developers/Javascript#Configuration) and share us outputs uses github [gist](https://gist.github.com/))*

**Steps to reproduce the behavior**
Log in (as user) with bogus credentials.

**Any others comments?**
The invokation of `.toLowerCase` is [here](https://github.com/QuickBlox/quickblox-javascript-sdk/commit/d3f4a09e851f523867e13f468608a70d3149cc39#diff-b8c46418c752126b90b724d1a10dfdec61be7b8d94f7f32410dc525cfb460c20R45).  Previously (in version 2.13.1), the `error.message` was directly compared to another string (which is false if `error.message` is `undefined`.  

However, now (in version 2.13.2), `error.message` is passed to `JSON.stringify` which results in `undefined`, whereupon the daisy-chained call to `.toLowerCase` fails with the above described exception :)

**Comment by nirajmchauhan** [comment] 2021-01-19 04:54
Facing the same issue, any solution to this?

**Comment by austin92jus** [comment] 2021-03-23 10:26
can you share the snapshot of your code ?

**Comment by ghost** [comment] 2021-10-07 15:10
@joelhelbling Hello,

This is Nikolay from QuickBlox support.

Please let me know if the issue is still relevant and if it can be reproduced with the last version of the SDK.

If yes, please provide be with more detailed instructions on how to reproduce the issue on my end.

**Comment by ghost** [comment] 2021-12-07 13:10
@joelhelbling @nirajmchauhan The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed as completed by ghost** 2021-12-07 13:10 UTC
