### ISSUE TITLE
Cannot recieve remote video on device without camera

### ISSUE THREAD

**Issue by Ascold2017** [QuickBlox/quickblox-javascript-sdk#388] opened 2020-05-12 17:44 UTC
**Environment details**
Windows 10 x64
Chrome  81.0.4044.129
SDK 2.12.7
Vue.js 2.6.10

**Did this work before?**
I have two PC devices: with a camera and without. When I calling from a device with camera to a device without a camera, second device received a video track from the caller (first device). But, when I calling from a device without a camera - I don't receive a video track from the remote participant (from a device, who has a camera).

**Expected behavior**
Participant, who don't have a camera device always receive video track from a remote participant, who has a camera device

**Actual behavior**
Participants, who don't have a camera device receive video track from a remote participant, who has a camera device only if caller has a camera device.

**Logs**
```
Creating video session:
const sessionType = QB.webrtc.CallType[isAvailableVideoDevice ? 'VIDEO' : 'AUDIO']; 
const session = QB.webrtc.createNewSession(participants, sessionType, rootState.quickBlox.userId, {
    bandwidth: '512'
});

const mediaParams = {
  audio: isAvailableAudioDevice,
  video: isAvailableVideoDevice,
  options: {
      muted: false,
      mirror: true
  }
};

session.getUserMedia(mediaParams, function(err: any, stream: any) {
    if (err) {
      reject(err);
    } else {
      session.localStream = stream;
      resolve(session);
    }
});

...
Accept Incoming call:

const mediaParams = {
    audio: isAvailableAudioDevice,
    video: isAvailableVideoDevice,
    options: {
       muted: false,
       mirror: true
    }
};

state.currentVideoSession.getUserMedia(mediaParams, function(err: any, stream: any) {
    if (err) throw err;
    state.currentVideoSession.accept({});
});

....

Listener:

QB.webrtc.onRemoteStreamListener = function(session: any, userId: any, remoteStream: MediaStream) {
              ...
      state.currentVideoSession.peerConnections[userId].stream = remoteStream;
      commit('SET_REMOTE_VIDEO_STREAM', remoteStream);
};

```

**Steps to reproduce the behavior**
1. Need 2 devices: first with camera device and second without it.
2. Call from the device without a camera.
3. Accept incoming call on device with a camera

**Any others comments?**
This problem also reproduces on webrtc example.

**Comment by ghost** [comment] 2021-10-07 15:01
Hello,

This is Nikolay from QuickBlox support.

Please try updating the SDK to the latest version:
[https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10](https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10)

Also, please try using our updated sample:
[https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/webrtc](https://github.com/QuickBlox/quickblox-javascript-sdk/tree/gh-pages/samples/webrtc)

**Comment by ghost** [comment] 2021-12-07 13:08
The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed as completed by ghost** 2021-12-07 13:08 UTC
