### ISSUE TITLE
Can not remove(delete) quickblox id

### ISSUE THREAD

**Issue by akhildev296** [QuickBlox/quickblox-javascript-sdk#390] opened 2020-05-27 15:16 UTC
When i try to delete a quickbloxid, i am getting an error

{ code: 404, status: 'error', message: '{"code":null,"message":"Possible subdomains: admin, api, billing"}', detail: null }

I really don't understand what this error message means.

 ```
QB.createSession(function(sessionErr: any, result: any) {
     if (sessionErr) {
       resolve({
         status: false,
         data: sessionErr,
       });
     }
     QB.users.delete(userId, function(err: any, result: any){
       console.log(" --> -->", result, err) 
       if (result) {
         resolve({
           status: true,
           data: result,
         });
       } else {
         resolve({
           status: false,
           data: err,
         });
       }
     });
   });
```

And i also tried creating users sessions as well but welcomed with the same result

**Comment by michelberbara** [comment] 2021-09-14 07:12
did you find any solution to that issue?

**Comment by ghost** [comment] 2021-10-07 15:06
Hello,

This is Nikolay from QuickBlox support.

Please let me know if the issue is still relevant.

If you want to remove a user, please follow our documentation:
[https://docs.quickblox.com/docs/js-users#delete-user](https://docs.quickblox.com/docs/js-users#delete-user)

If the issue persists, please provide me with:
1. Full logs.
2. Steps to reproduce the issue.
3. More detailed description of the issue.
4. Specify used browsers.
5. Please clarify if the issue is reproduced on the latest version of the SDK:
[https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10](https://github.com/QuickBlox/quickblox-javascript-sdk/releases/tag/2.13.10)

**Comment by ghost** [comment] 2021-12-07 13:08
@michelberbara @akhildev296 The issue is being closed as outdated.

If it is still relevant, feel free to open a new issue.

**Closed as completed by ghost** 2021-12-07 13:08 UTC
